[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.85
blur = true

[window.padding]
x = 4
y = 4

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 10

[keyboard]
bindings = [
    { key = "C", mods = "Control", action = "Copy" },
    { key = "C", mods = "Control | Shift", chars = "\u0003"}
]
