[[manager.prepend_keymap]]
on = [ "e", "s" ]
run = '''
    shell '"$1"' --block
''' 
desc = "Exec scipt"

[[manager.prepend_keymap]]
on = [ "e", "d" ]
run = '''
    shell 'dragon -x -i -T "$1"' --confirm
''' 
desc = "Exec drag and drop"

[[manager.prepend_keymap]]
on  = "y"
run = [ '''
    shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]

[[manager.prepend_keymap]]
# Mnemonic: "[F]ull-size preview"
on   = "F"
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
# (Normally, "Seek down 5 units in the preview".)
# See: https://yazi-rs.github.io/docs/tips#parent-arrow
on  = "J"
run = "plugin --sync parent-arrow --args=1"
desc = "Navigate down in the parent directory without changing focus"

[[manager.prepend_keymap]]
# (Normally, "Seek up 5 units in the preview".)
# See: https://yazi-rs.github.io/docs/tips#parent-arrow
on  = "K"
run = "plugin --sync parent-arrow --args=-1"
desc = "Navigate up in the parent directory without changing focus"

[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Go to ~/Downloads"

[[manager.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd /home/dias/Work/core/services"
desc = "Go to local Protei services"

[[manager.prepend_keymap]]
on   = [ "g", "S" ]
run  = "cd /home/protei/Protei-UC/"
desc = "Go to root Protei services"

[[manager.prepend_keymap]]
on   = [ "g", "r" ]
run  = "cd /root"
desc = "Go to root home"

[[manager.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[manager.prepend_keymap]]
on   = [ "u", "z" ]
run = '''
    shell 'unzip "$1"' --confirm
''' 
desc = "Unpack zip archive"

[[manager.prepend_keymap]]
on   = [ "u", "t" ]
run = '''
    shell 'tar xvf "$1"' --confirm
''' 
desc = "Unpack tar archive"

[[manager.prepend_keymap]]
on   = [ "u", "g" ]
run = '''
    shell 'tar xzvf "$1"' --confirm
''' 
desc = "Unpack tar[.gz|.bz2|.xz] archive"

[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Compress archive"

[[manager.prepend_keymap]]
on = [ ";" ]
run  = '''
    shell 'tmux popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E "tmux attach-session -t popup || tmux new-session -s popup"'
'''
desc = "Drop to shell"

[[manager.prepend_keymap]]
on = [ "<C-;>" ]
run  = "plugin command"
desc = "Yazi command prompt"
