# [preview]
# ueberzug_scale = 1.8
# ueberzug_offset = [-14, 3, 0, 0]

[plugin]
prepend_previewers = [
	# HEIC previewer
	{ mime = "image/heic", run = "heic" },
	{ mime = "video/x-matroska", run = "/var/lib/flatpak/exports/bin/org.kde.haruna '$@'" },
    { name = "*.md", run = "glow" },
]
append_previewers = [
	# My fallback previewer
	{ name = "*" , run = "binary" },
]

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
markdown = [
	{ run = 'glow', block = true },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
prepend_rules = [
	{ name = "*.md", use = "markdown" },
]
append_rules = [
	{ name = "*", use = [ "open", "text" ] },
]
#
# [open]
# rules = [
# 	{ name = "*.md", use = "markdown" },
#     { name = "*", use = "text" },
# ]
